name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Inject GitHub Token and Password
      run: |
        mkdir -p secure-page
        echo "window.VIZ_TOKEN = '${{ secrets.VIZ_TOKEN }}';" > secure-page/config.js
        echo "window.PASSWORD = '${{ secrets.PASSWORD }}';" >> secure-page/config.js
        echo "window.REPO_NAME = '${{ secrets.REPO_NAME }}';" >> secure-page/config.js
        echo "window.DIRECTORY_PATH = 'lab-bench-reports-precision';" >> secure-page/config.js
    - name: Verify Config JS
      run: |
        if grep -q "window.VIZ_TOKEN = '';" secure-page/config.js; then echo "VIZ_TOKEN is missing"; exit 1; fi
        if grep -q "window.PASSWORD = '';" secure-page/config.js; then echo "PASSWORD is missing"; exit 1; fi
        if grep -q "window.REPO_NAME = '';" secure-page/config.js; then echo "REPO_NAME is missing"; exit 1; fi
        if grep -q "window.DIRECTORY_PATH = '';" secure-page/config.js; then echo "DIRECTORY_PATH is missing"; exit 1; fi
    - name: List Directory Structure
      run: |
        ls -R
    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add secure-page/config.js
        git commit -m "Add secure-page/config.js"
        git push origin master
